import { readdirSync } from 'fs'
import { basename, dirname, join } from 'path'

/**
 * GoPro writes a small, fast-start-optimized H.264 proxy sidecar alongside every main chapter file
 * it records -- e.g. GH010230.MP4 (chapter 01, session 0230) has a matching GL010230.LRV in the
 * same directory. Only the camera itself writes these (never generated by this app), and they're
 * commonly left behind when only the main .MP4 is copied off a card, so their absence is the normal
 * case, not an error.
 *
 * Matched case-insensitively (camera firmware/OS casing isn't perfectly consistent) by listing the
 * directory rather than guessing a single exact-case path.
 */
export function findLrvSibling(videoPath: string): string | null {
  const match = /^G[HX](\d{6})\.(mp4|mov)$/i.exec(basename(videoPath))
  if (!match) return null

  const expectedName = `gl${match[1]}.lrv`
  const dir = dirname(videoPath)
  let entries: string[]
  try {
    entries = readdirSync(dir)
  } catch {
    return null
  }

  const found = entries.find((entry) => entry.toLowerCase() === expectedName)
  return found ? join(dir, found) : null
}
